#!/usr/bin/env bash
# gen-glyphs.sh — extract the exact Nerd Font glyph bytes from the teleport
# source so the simulations stay byte-faithful to the real CLI. Regenerate with:
#   bash demo/sim/gen-glyphs.sh > demo/sim/glyphs.sh
set -euo pipefail
cd "$(dirname "$0")/../.."

python3 - <<'PY'
import re, shlex

tui = open("internal/tui/syncprogress.go").read()
fp  = open("internal/tui/filepicker.go").read()
bf  = open("internal/tui/beamfilepicker.go").read()
cp  = open("internal/tui/commitpicker.go").read()
dp  = open("internal/tui/dirpicker.go").read()
hp  = open("internal/tui/hostpicker.go").read()
br  = open("internal/tui/branchpicker.go").read()
hlp = open("cmd/help.go").read()
sh_ = open("cmd/ship.go").read()

def const_dq(text, name):
    m = re.search(name + r'\s*=\s*"([^"]+)"', text)
    return m.group(1).strip() if m else ""

def rune_sq(text, name):
    m = re.search(name + r"\s*=\s*'([^']+)'", text)
    return m.group(1) if m else ""

def mapico(text, key):
    m = re.search(r'"' + re.escape(key) + r'":\s*"([^"]+)"', text)
    return m.group(1) if m else ""

def caseico(text, key):
    m = re.search(r'case "' + re.escape(key) + r'":\s*\n\s*return "([^"]+)"', text)
    return m.group(1) if m else ""

vals = {
    "G_DELETE":   const_dq(bf, "iconDelete"),
    "G_CUBE":     const_dq(bf, "iconCube"),
    "G_FILE":     const_dq(fp, "iconFile"),
    "G_CHECKED":  const_dq(fp, "iconChecked"),
    "G_FOLDER":   const_dq(dp, "iconFolder"),
    "G_BRANCH":   const_dq(br, "iconBranch"),
    "G_MAIN":     const_dq(br, "iconMain"),
    "G_COMMIT":   const_dq(cp, "iconCommit"),
    "G_SENT":     const_dq(cp, "iconSent"),
    "G_SERVER":   const_dq(hp, "iconServer"),
    "G_PERSON":   rune_sq(hlp, "iconPerson"),
    "G_SYNC":     rune_sq(hlp, "iconSync"),
    "G_GEAR":     rune_sq(hlp, "iconGear"),
    "G_GO":       mapico(tui, "go"),
    "G_TS":       mapico(tui, "ts"),
    "G_PY":       mapico(tui, "py"),
    "G_MD":       mapico(tui, "md"),
    "G_JSON":     mapico(tui, "json"),
    "G_YML":      mapico(tui, "yml"),
    "G_YAML":     mapico(tui, "yaml"),
    "G_CSS":      mapico(tui, "css"),
    "G_SH":       mapico(tui, "sh"),
    "G_TOML":     mapico(tui, "toml"),
    "G_SQL":      mapico(tui, "sql"),
    "G_DOCKER":   caseico(tui, "dockerfile"),
    "G_MAKE":     caseico(tui, "makefile"),
}
def ship_g(pat):
    m = re.search(r'"(\S+)\s+' + pat, sh_)
    return m.group(1) if m else ""
vals["G_SHIP"]   = ship_g("Shipping")
vals["G_UPLOAD"] = ship_g("uploading")
vals["G_RENAME"] = ship_g("renaming")
vals["G_CHMOD"]  = ship_g("chmod")
vals["G_MOVE"]   = ship_g("moving")

m = re.search(r'return "([^"]+)" // cod-file', tui)
vals["G_FALLBACK"] = m.group(1) if m else ""
m = re.search(r'\.gitignore"[^\n]*:\s*\n\s*return "([^"]+)"', tui)
vals["G_GITIGNORE"] = m.group(1) if m else ""

print("#!/usr/bin/env bash")
print("# AUTO-GENERATED by gen-glyphs.sh — do not edit. Nerd Font glyphs from teleport source.")
for k, v in vals.items():
    print("%s=%s" % (k, shlex.quote(v)))
PY
